# Map
map: 
  map_name: 'map_pen'
  # map_name: 'map_wareh'

# Robot 
robot:
  total_robots: 8
  robot_start_w: # for warehouse map
    1: [-1.5,-22.5,0.0]
    2: [7.5,19.5,0.0]
    3: [4.5,-16.5,0.0]
    4: [4.5,-19.5,0.0]
  robot_start_p: # for pendora
    1: [1.5,-64.5,0.0]
    2: [-1.5,-64.5,0.0]
    3: [4.5,-61.5,0.0]
    #4: [-1.5,-37.5 ,0.0]
    4: [4.5,-58.5 ,0.0]
    5: [-1.5,-31.5,0.0]
    6: [-1.5,-40.5,0.0]    
    7: [4.5,-28.5,0.0]
    8: [4.5,-25.5,0.0]
    # 9: [-4.5,-28.5,0.0]
    # 10: [-4.5,-25.5,0.0]




# A-star config 
costs:  
  #backward: 1.0
  backward: 2.5
  stop: 1.0
  straight: 0.25
  rotate_left: 0.5
  rotate_right: 0.5
  # straight: 0.6
  # rotate_left: 0.1
  # rotate_right: 0.1